#!/bin/bash

# SEE
#
#
# https://bugs.python.org/issue22625
# When cross-compiling, don't try to execute binaries
# 
# https://bugs.python.org/issue19142
# Cross-compile fails trying to execute foreign pgen on build host
# 
# https://vstinner.github.io/contrib-cpython-2017q2-part1.html
# Rename PYTHON_FOR_GEN to PYTHON_FOR_REGEN
#
# https://bugs.python.org/file43829/py_for_gen_26662_3.patch
# Add PYTHON_FOR_GEN
#
# https://bugs.python.org/file44732/PYTHON_FOR_GEN.patch
# Configure now searches for commands called python2.7, python2, and python,
and sets PYTHON_FOR_GEN to the result

#
# https://bugs.python.org/issue35808
# Let's retire PGEN
#


source /Applications/Momentics.app/bbndk-env_10_3_1_995.sh

export PBHOSTARCH=arm-unknown-nto-qnx8.0.0eabi
export PBBUILDARCH=`gcc -dumpmachine`
export PBTARGETARCH=arm-unknown-nto-qnx8.0.0eabi


export PATH="/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features//jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features/com.qnx.tools.jre.macosx.x86_64_1.7.0.51/jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features/com.qnx.tools.jre.macosx.x86_64_1.7.0.51/jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:~/xsh/bin"

make 
exit 0

type hg || {
	echo
	echo "Warning: build process may need "hg" (aka Mercurial VCS)"
	echo
	sleep 1
}

export CFLAGS='-DDISABLE_ASDLGEN -DPY_FORMAT_LONG_LONG=\"ll\"' 
../Python-3/configure --host=$PBHOSTARCH  --build=$PBBUILDARCH --target=$PBTARGETARCH --prefix=$PREFIX  CC=$PBTARGETARCH-gcc 

for patch in $(ls ../patches/*patch)
do
	patch < $patch
done

make -j2
