#!/bin/bash


source /Applications/Momentics.app/bbndk-env_10_3_1_995.sh

export PBHOSTARCH=arm-unknown-nto-qnx8.0.0eabi
export PBBUILDARCH=`gcc -dumpmachine`
export PBTARGETARCH=arm-unknown-nto-qnx8.0.0eabi


export PATH="/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features//jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features/com.qnx.tools.jre.macosx.x86_64_1.7.0.51/jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/bin:/Users/testuser/Library/Research In Motion/BlackBerry Native SDK/bin:/Applications/Momentics.app/features/com.qnx.tools.jre.macosx.x86_64_1.7.0.51/jre/Contents/Home/bin:/Applications/Momentics.app/host_10_3_1_12/darwin/x86/usr/python32/bin:~/xsh/bin"


type hg || {
	echo
	echo "Warning: build process may need "hg" (aka Mercurial VCS)"
	echo
	sleep 1
}

export CFLAGS='-DDISABLE_ASDLGEN -DPY_FORMAT_LONG_LONG=\"ll\"' 
../Python-3/configure --host=$PBHOSTARCH  --build=$PBBUILDARCH --target=$PBTARGETARCH --prefix=$PREFIX  CC=$PBTARGETARCH-gcc 

for patch in $(ls ../patches/*patch)
do
	patch < $patch
done

make -j2
